project:
  type: website
  output-dir: docs

website:
  title: "semob-mcid.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - qmds/base.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



