project:
  type: website
  output-dir: docs

website:
  title: "semob-mcid.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Bases
        menu:
        - text: Base Ativos
          href: qmds/base.qmd
        - text: Base PAC
          href: qmds/base_pac.qmd
        
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


lang: pt-BR
